require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TopicosController do

  # This should return the minimal set of attributes required to create a valid
  # Topico. As you add validations to Topico, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all topicos as @topicos" do
      topico = Topico.create! valid_attributes
      get :index
      assigns(:topicos).should eq([topico])
    end
  end

  describe "GET show" do
    it "assigns the requested topico as @topico" do
      topico = Topico.create! valid_attributes
      get :show, :id => topico.id.to_s
      assigns(:topico).should eq(topico)
    end
  end

  describe "GET new" do
    it "assigns a new topico as @topico" do
      get :new
      assigns(:topico).should be_a_new(Topico)
    end
  end

  describe "GET edit" do
    it "assigns the requested topico as @topico" do
      topico = Topico.create! valid_attributes
      get :edit, :id => topico.id.to_s
      assigns(:topico).should eq(topico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Topico" do
        expect {
          post :create, :topico => valid_attributes
        }.to change(Topico, :count).by(1)
      end

      it "assigns a newly created topico as @topico" do
        post :create, :topico => valid_attributes
        assigns(:topico).should be_a(Topico)
        assigns(:topico).should be_persisted
      end

      it "redirects to the created topico" do
        post :create, :topico => valid_attributes
        response.should redirect_to(Topico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved topico as @topico" do
        # Trigger the behavior that occurs when invalid params are submitted
        Topico.any_instance.stub(:save).and_return(false)
        post :create, :topico => {}
        assigns(:topico).should be_a_new(Topico)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Topico.any_instance.stub(:save).and_return(false)
        post :create, :topico => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested topico" do
        topico = Topico.create! valid_attributes
        # Assuming there are no other topicos in the database, this
        # specifies that the Topico created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Topico.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => topico.id, :topico => {'these' => 'params'}
      end

      it "assigns the requested topico as @topico" do
        topico = Topico.create! valid_attributes
        put :update, :id => topico.id, :topico => valid_attributes
        assigns(:topico).should eq(topico)
      end

      it "redirects to the topico" do
        topico = Topico.create! valid_attributes
        put :update, :id => topico.id, :topico => valid_attributes
        response.should redirect_to(topico)
      end
    end

    describe "with invalid params" do
      it "assigns the topico as @topico" do
        topico = Topico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Topico.any_instance.stub(:save).and_return(false)
        put :update, :id => topico.id.to_s, :topico => {}
        assigns(:topico).should eq(topico)
      end

      it "re-renders the 'edit' template" do
        topico = Topico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Topico.any_instance.stub(:save).and_return(false)
        put :update, :id => topico.id.to_s, :topico => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested topico" do
      topico = Topico.create! valid_attributes
      expect {
        delete :destroy, :id => topico.id.to_s
      }.to change(Topico, :count).by(-1)
    end

    it "redirects to the topicos list" do
      topico = Topico.create! valid_attributes
      delete :destroy, :id => topico.id.to_s
      response.should redirect_to(topicos_url)
    end
  end

end
